---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates (CentOS)
    tags: always  
    dnf:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install udates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"  
   
- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php package for web servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"